// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgoJ0d7lyGrSzYGqrvOH7qBRu3AUL2Ko',
    appId: '1:761505936107:web:18d112534464836de8c4ae',
    messagingSenderId: '761505936107',
    projectId: 'chatup-939ba',
    authDomain: 'chatup-939ba.firebaseapp.com',
    storageBucket: 'chatup-939ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGa2btxVqdFc37mF9KhBguSWGBAtq9Ik',
    appId: '1:761505936107:android:3e22aa3b0d62e8cde8c4ae',
    messagingSenderId: '761505936107',
    projectId: 'chatup-939ba',
    storageBucket: 'chatup-939ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4avSnwQVjvuMXJ8yKbXxFB8_oHyrTH34',
    appId: '1:761505936107:ios:c5983e93a906bc4fe8c4ae',
    messagingSenderId: '761505936107',
    projectId: 'chatup-939ba',
    storageBucket: 'chatup-939ba.firebasestorage.app',
    iosBundleId: 'com.example.chatUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4avSnwQVjvuMXJ8yKbXxFB8_oHyrTH34',
    appId: '1:761505936107:ios:c5983e93a906bc4fe8c4ae',
    messagingSenderId: '761505936107',
    projectId: 'chatup-939ba',
    storageBucket: 'chatup-939ba.firebasestorage.app',
    iosBundleId: 'com.example.chatUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgoJ0d7lyGrSzYGqrvOH7qBRu3AUL2Ko',
    appId: '1:761505936107:web:55bf7861033aab73e8c4ae',
    messagingSenderId: '761505936107',
    projectId: 'chatup-939ba',
    authDomain: 'chatup-939ba.firebaseapp.com',
    storageBucket: 'chatup-939ba.firebasestorage.app',
  );
}
